//Criação de usuário
POST http://localhost:3003/user
Content-Type: application/json

{
    "name": "Lab Bot",
    "nickname": "botinho",
    "email": "bot@dev.com"
}

###

//Pegar todos os usuários
GET http://localhost:3003/user

###

//Pegar um usuário por id
GET http://localhost:3003/user/1

###

//Editar um usuário por id
PUT http://localhost:3003/user/edit/1
Content-Type: application/json

{
    "email": "@strodev.com"
}

###

//Criar tarefa
POST http://localhost:3003/task
Content-Type: application/json

{
    "title": "Patrícia",
    "description": "Fazer o projeto ToDoList",
    "limitDate": "01/07/2022"
}

###

//Pegar tarefa pelo id
GET http://localhost:3003/task/1